#!/bin/sh
unicode="▅▅▅"
version="1.2.0"

_black=$(tput setaf 0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
_white=$(tput setaf 7)
_bright=$(tput bold)
normal=$(tput sgr0)
_underline=$(tput smul)

help() {
printf "Usage:
    -v, --version
      prints maxfetch version
    -u, --update
      updates maxfetch
    -h, --help
      prints this message
"
}

up=$(uptime | sed -E 's/^[^,]*up *//; s/mins/minutes/; s/hrs?/hours/;
  s/([[:digit:]]+):0?([[:digit:]]+)/\1 hours, \2 minutes/;
  s/^1 hours/1 hour/; s/ 1 hours/ 1 hour/;
  s/min,/minutes,/; s/ 0 minutes,/ less than a minute,/; s/ 1 minutes/ 1 minute/;
  s/  / /; s/, *[[:digit:]]* users?.*//')

fetch() {
    echo "┌────────────┐ "
    echo "│  ${red}user${normal}      │ ${red}$(whoami)${normal}"
    echo "│  ${yellow}hname${normal}     │ ${yellow}$(cat /etc/hostname)${normal} "
    echo "│  ${green}distro${normal}    │ ${green}$(sed -nE "s@PRETTY_NAME=\"([^\"]*)\"@\1@p" /etc/os-release)${normal} "
    echo "│  ${cyan}kernel${normal}    │ ${cyan}$(uname -r)${normal} "
    echo "│  ${blue}de/wm${normal}     │ ${blue}$XDG_CURRENT_DESKTOP${normal} "
    echo "│  ${magenta}uptime${normal}    │ ${magenta}${up}${normal} "
    echo "│  ${red}shell${normal}     │ ${red}$(echo ${SHELL##*/})${normal} "
    echo "│  ${yellow}term${normal}      │ ${yellow}$(ps -o comm= -p "$(($(ps -o ppid= -p "$(($(ps -o sid= -p "$$")))")))")${normal} "
    echo "├────────────┤ "
    echo "│  ${yellow}colors${normal}    │ ${red}$unicode${normal}${yellow}$unicode${normal}${green}$unicode${normal}${cyan}$unicode${normal}${blue}$unicode${normal}${magenta}$unicode${normal}"
    echo "└────────────┘ "
}
update() {
	update=$(curl -s "https://raw.githubusercontent.com/jobcmax/maxfetch/main/maxfetch" || die "Connection error")
	update="$(printf '%s\n' "$update" | diff -u "$(which maxfetch)" -)"
	if [ -z "$update" ]; then
		printf "Script is up to date :)\n"
	else
		if printf '%s\n' "$update" | patch "$(which maxfetch)" -; then
			printf "Script has been updated\n"
		else
			printf "Can't update for some reason!\n"
		fi
	fi
	exit 0
}
while [ $# -gt 0 ]; do
	case "$1" in
	-v | --version) printf "Maxfetch %s\n" "$version" && exit 0 ;;
  -u | --update) update ;;
  -h | --help) help && exit 0 ;;
  *) fetch && exit 0 ;;
	esac
done
fetch && exit 0
